name: Upgrade dependencies
on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:

jobs:
  upgrade:
    name: Upgrade dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: renovatebot/github-action@v44.2.0
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        configurationFile: ./renovatebot.json
