name: Upgrade dependencies
on:
  schedule:
  - cron: "30 17 * * 5" # Friday afternoon
  workflow_dispatch:

jobs:
  upgrade:
    name: Upgrade dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: renovatebot/github-action@v43.0.17
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}
        configurationFile: .github/renovatebot.json
